#include <iostream>

void PlayGame() {

}

int main(){
    try {
        PlayGame();
    }
    catch (std::exception err) {

    }
}
